## Homework for the class "Advanced Data Analysis with Python"

We will start with some basic exercises with Pandas, Seaborn and NumPy. To solve the exercise, you can refer to their **official documentation**:
 - [Pandas](https://pandas.pydata.org/docs/)
 - [NumPy](https://numpy.org/doc/stable/)
 - [Seaborn](https://seaborn.pydata.org/)

## Dataset exploration
### `Pandas` first

Now, let's open again the dataset that we used in class:

In [21]:
# Open the dataset

import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("yasserh/housing-prices-dataset")
#path = kagglehub.dataset_download("ignacioazua/world-gdp-population-and-co2-emissions-dataset")

print("Path to dataset files:", path)

print("Path to dataset files:", path) # Path to the downloaded folder 
filename = os.listdir(path)
print(filename) # Shows content of the folder
#filepath=os.path.join(path, "World_GDP_Population_CO2_Emissions_Dataset.csv")
filepath=os.path.join(path, "Housing.csv")
print(filepath)

Path to dataset files: /home/cgraiff/.cache/kagglehub/datasets/yasserh/housing-prices-dataset/versions/1
Path to dataset files: /home/cgraiff/.cache/kagglehub/datasets/yasserh/housing-prices-dataset/versions/1
['Housing.csv']
/home/cgraiff/.cache/kagglehub/datasets/yasserh/housing-prices-dataset/versions/1/Housing.csv

In [22]:
# Importing necessary libraries for the analysis

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [23]:
# Read dataset into a pandas dataframe
df = pd.read_csv(filepath) 

# Visualize the first 5 rows
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

### Description
Get a summary of the dataframe and inspect it. Use the methods introduced in class.

In [24]:
# Insert your code here
df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

### Dataframe Manipulation

- Create a boolean column has_air_conditioning.
- Create a boolean column has_4_bedrooms.

In [39]:
# Insert your code here
df['has_air_conditioning'] = df['basement'] == "yes"
df['has_4_bedrooms'] = df['bedrooms'] >= 4
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,has_air_conditioning,has_4_bedrooms
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,False,True
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,False,True
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,True,False
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,True,True
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished,True,False
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished,False,False
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished,False,False
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished,False,False
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished,False,False

### Filtering

- Sort the DataFrame by area descending.

- Sort by area ascending, then by price descending.

In [43]:
# Insert your code here
df_sorted_asc = df.sort_values(by='area', ascending=False)
#print(df_sorted_asc)
df_sorted_pricearea = df.sort_values(by=['area', 'price'], ascending=[True, False])
print(df_sorted_pricearea)

        price   area  bedrooms  bathrooms  stories mainroad guestroom  \
449   3150000   1650         3          1        2       no        no
537   1890000   1700         3          1        2      yes        no
527   2275000   1836         2          1        1       no        no
271   4340000   1905         5          1        2       no        no
413   3430000   1950         3          2        2      yes        no
..        ...    ...       ...        ...      ...      ...       ...
403   3500000  12944         3          1        1      yes        no
10    9800000  13200         3          1        2      yes        no
66    6930000  13200         2          1        1      yes        no
125   5943000  15600         3          1        1      yes        no
7    10150000  16200         5          3        2      yes        no

    basement hotwaterheating airconditioning  parking prefarea  \
449      yes              no              no        0       no
537       no              no              no        0       no
527      yes              no              no        0       no
271      yes              no              no        0       no
413      yes              no              no        0      yes
..       ...             ...             ...      ...      ...
403       no              no              no        0       no
10       yes              no             yes        2      yes
66       yes             yes              no        1       no
125       no              no             yes        2       no
7         no              no              no        0       no

    furnishingstatus  has_air_conditioning  has_4_bedrooms
449      unfurnished                  True           False
537      unfurnished                 False           False
527   semi-furnished                  True           False
271   semi-furnished                  True            True
413      unfurnished                  True           False
..               ...                   ...             ...
403      unfurnished                 False           False
10         furnished                  True           False
66         furnished                  True           False
125   semi-furnished                 False           False
7        unfurnished                 False            True

[545 rows x 15 columns]

> In this case, `pandas` first sorts by area (primary key). Within rows that have the same value in area, it sorts by price (secondary key).

### Re-sampling, shuffling

- Randomly sample 5 rows from the DataFrame.

- Shuffle all rows of the DataFrame.

In [44]:
# Insert your code here
sampled_df = df.sample(n=5, random_state=42)  # random_state ensures reproducibility
print(sampled_df)

       price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
316  4060000  5900         4          2        2       no        no      yes
77   6650000  6500         3          2        3      yes        no       no
360  3710000  4040         2          1        1      yes        no       no
90   6440000  5000         3          1        2      yes        no       no
493  2800000  3960         3          1        1      yes        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus  \
316              no              no        1       no      unfurnished
77               no             yes        0      yes        furnished
360              no              no        0       no   semi-furnished
90               no             yes        0       no   semi-furnished
493              no              no        0       no        furnished

     has_air_conditioning  has_4_bedrooms
316                  True            True
77                  False           False
360                 False           False
90                  False           False
493                 False           False

In [47]:
# Eventually:
sampled_df_price_area = df.sample(n=5)[['price', 'area']]
print(sampled_df_price_area)

       price  area
184  5110000  3000
455  3129000  5495
508  2590000  4400
204  4900000  4770
303  4200000  4500

In [48]:
df_shuffled = df.sample(frac=1, random_state=42)  # frac is the fraction of rows to return, 1 = 100%
print(df_shuffled)

       price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
316  4060000  5900         4          2        2       no        no      yes
77   6650000  6500         3          2        3      yes        no       no
360  3710000  4040         2          1        1      yes        no       no
90   6440000  5000         3          1        2      yes        no       no
493  2800000  3960         3          1        1      yes        no       no
..       ...   ...       ...        ...      ...      ...       ...      ...
71   6755000  6000         4          2        4      yes        no       no
106  6160000  5450         4          2        1      yes        no      yes
270  4340000  4500         3          2        3      yes        no       no
435  3290000  4040         2          1        1      yes        no       no
102  6195000  5500         3          2        4      yes       yes       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus  \
316              no              no        1       no      unfurnished
77               no             yes        0      yes        furnished
360              no              no        0       no   semi-furnished
90               no             yes        0       no   semi-furnished
493              no              no        0       no        furnished
..              ...             ...      ...      ...              ...
71               no             yes        0       no      unfurnished
106              no             yes        0      yes   semi-furnished
270             yes              no        1       no        furnished
435              no              no        0       no      unfurnished
102              no             yes        1       no   semi-furnished

     has_air_conditioning  has_4_bedrooms
316                  True            True
77                  False           False
360                 False           False
90                  False           False
493                 False           False
..                    ...             ...
71                  False            True
106                  True            True
270                 False           False
435                 False           False
102                 False           False

[545 rows x 15 columns]

## Visualization
### We will now use visualization libraries such as `Seaborn` and `Matplotlib`.
During the last lesson, **there were some questions about `pairplot()`**. By default, `pairplot()` generates a matrix of scatterplots. On the diagonal of the matrix, `pairplot()` generates histograms. As we said, it is possible to customize this function.
Explore the documentation of this function: https://seaborn.pydata.org/generated/seaborn.pairplot.html and come up with an interesting visualization of your choice that you can interpret.

In [28]:
# Insert code here

## Numerical computing
### `NumPy` time!

Now, let's do some NumPy exercises. To do so, let's convert some columns of the Pandas dataframe into a NumPy array.
Remember, NumPy is useful for **numerical computation**!

In [29]:
col_price = df['price'].to_numpy()
col_area = df['area'].to_numpy()
col_price_area = df[['price', 'area']].to_numpy()

In [30]:
print(col_price)

[13300000 12250000 12250000 12215000 11410000 10850000 10150000 10150000
  9870000  9800000  9800000  9681000  9310000  9240000  9240000  9100000
  9100000  8960000  8890000  8855000  8750000  8680000  8645000  8645000
  8575000  8540000  8463000  8400000  8400000  8400000  8400000  8400000
  8295000  8190000  8120000  8080940  8043000  7980000  7962500  7910000
  7875000  7840000  7700000  7700000  7560000  7560000  7525000  7490000
  7455000  7420000  7420000  7420000  7350000  7350000  7350000  7350000
  7343000  7245000  7210000  7210000  7140000  7070000  7070000  7035000
  7000000  6930000  6930000  6895000  6860000  6790000  6790000  6755000
  6720000  6685000  6650000  6650000  6650000  6650000  6650000  6650000
  6629000  6615000  6615000  6580000  6510000  6510000  6510000  6475000
  6475000  6440000  6440000  6419000  6405000  6300000  6300000  6300000
  6300000  6300000  6293000  6265000  6230000  6230000  6195000  6195000
  6195000  6160000  6160000  6125000  6107500  6090000  6090000  6090000
  6083000  6083000  6020000  6020000  6020000  5950000  5950000  5950000
  5950000  5950000  5950000  5950000  5950000  5943000  5880000  5880000
  5873000  5873000  5866000  5810000  5810000  5810000  5803000  5775000
  5740000  5740000  5740000  5740000  5740000  5652500  5600000  5600000
  5600000  5600000  5600000  5600000  5600000  5600000  5600000  5565000
  5565000  5530000  5530000  5530000  5523000  5495000  5495000  5460000
  5460000  5460000  5460000  5425000  5390000  5383000  5320000  5285000
  5250000  5250000  5250000  5250000  5250000  5250000  5250000  5250000
  5250000  5243000  5229000  5215000  5215000  5215000  5145000  5145000
  5110000  5110000  5110000  5110000  5075000  5040000  5040000  5040000
  5040000  5033000  5005000  4970000  4970000  4956000  4935000  4907000
  4900000  4900000  4900000  4900000  4900000  4900000  4900000  4900000
  4900000  4900000  4900000  4900000  4893000  4893000  4865000  4830000
  4830000  4830000  4830000  4795000  4795000  4767000  4760000  4760000
  4760000  4753000  4690000  4690000  4690000  4690000  4690000  4690000
  4655000  4620000  4620000  4620000  4620000  4620000  4613000  4585000
  4585000  4550000  4550000  4550000  4550000  4550000  4550000  4550000
  4543000  4543000  4515000  4515000  4515000  4515000  4480000  4480000
  4480000  4480000  4480000  4473000  4473000  4473000  4445000  4410000
  4410000  4403000  4403000  4403000  4382000  4375000  4340000  4340000
  4340000  4340000  4340000  4319000  4305000  4305000  4277000  4270000
  4270000  4270000  4270000  4270000  4270000  4235000  4235000  4200000
  4200000  4200000  4200000  4200000  4200000  4200000  4200000  4200000
  4200000  4200000  4200000  4200000  4200000  4200000  4200000  4200000
  4193000  4193000  4165000  4165000  4165000  4130000  4130000  4123000
  4098500  4095000  4095000  4095000  4060000  4060000  4060000  4060000
  4060000  4025000  4025000  4025000  4007500  4007500  3990000  3990000
  3990000  3990000  3990000  3920000  3920000  3920000  3920000  3920000
  3920000  3920000  3885000  3885000  3850000  3850000  3850000  3850000
  3850000  3850000  3850000  3836000  3815000  3780000  3780000  3780000
  3780000  3780000  3780000  3773000  3773000  3773000  3745000  3710000
  3710000  3710000  3710000  3710000  3703000  3703000  3675000  3675000
  3675000  3675000  3640000  3640000  3640000  3640000  3640000  3640000
  3640000  3640000  3640000  3633000  3605000  3605000  3570000  3570000
  3570000  3570000  3535000  3500000  3500000  3500000  3500000  3500000
  3500000  3500000  3500000  3500000  3500000  3500000  3500000  3500000
  3500000  3500000  3500000  3500000  3493000  3465000  3465000  3465000
  3430000  3430000  3430000  3430000  3430000  3430000  3423000  3395000
  3395000  3395000  3360000  3360000  3360000  3360000  3360000  3360000
  3360000  3360000  3353000  3332000  3325000  3325000  3290000  3290000
  3290000  3290000  3290000  3290000  3290000  3290000  3255000  3255000
  3234000  3220000  3220000  3220000  3220000  3150000  3150000  3150000
  3150000  3150000  3150000  3150000  3150000  3150000  3143000  3129000
  3118850  3115000  3115000  3115000  3087000  3080000  3080000  3080000
  3080000  3045000  3010000  3010000  3010000  3010000  3010000  3010000
  3010000  3003000  2975000  2961000  2940000  2940000  2940000  2940000
  2940000  2940000  2940000  2940000  2870000  2870000  2870000  2870000
  2852500  2835000  2835000  2835000  2800000  2800000  2730000  2730000
  2695000  2660000  2660000  2660000  2660000  2660000  2660000  2660000
  2653000  2653000  2604000  2590000  2590000  2590000  2520000  2520000
  2520000  2485000  2485000  2450000  2450000  2450000  2450000  2450000
  2450000  2408000  2380000  2380000  2380000  2345000  2310000  2275000
  2275000  2275000  2240000  2233000  2135000  2100000  2100000  2100000
  1960000  1890000  1890000  1855000  1820000  1767150  1750000  1750000
  1750000]

In [31]:
print(col_area)

[ 7420  8960  9960  7500  7420  7500  8580 16200  8100  5750 13200  6000
  6550  3500  7800  6000  6600  8500  4600  6420  4320  7155  8050  4560
  8800  6540  6000  8875  7950  5500  7475  7000  4880  5960  6840  7000
  7482  9000  6000  6000  6550  6360  6480  6000  6000  6000  6000  6600
  4300  7440  7440  6325  6000  5150  6000  6000 11440  9000  7680  6000
  6000  8880  6240  6360 11175  8880 13200  7700  6000 12090  4000  6000
  5020  6600  4040  4260  6420  6500  5700  6000  6000  4000 10500  6000
  3760  8250  6670  3960  7410  8580  5000  6750  4800  7200  6000  4100
  9000  6400  6600  6000  6600  5500  5500  6350  5500  4500  5450  6420
  3240  6615  6600  8372  4300  9620  6800  8000  6900  3700  6420  7020
  6540  7231  6254  7320  6525 15600  7160  6500  5500 11460  4800  5828
  5200  4800  7000  6000  5400  4640  5000  6360  5800  6660 10500  4800
  4700  5000 10500  5500  6360  6600  5136  4400  5400  3300  3650  6100
  6900  2817  7980  3150  6210  6100  6600  6825  6710  6450  7800  4600
  4260  6540  5500 10269  8400  5300  3800  9800  8520  6050  7085  3180
  4500  7200  3410  7980  3000  3000 11410  6100  5720  3540  7600 10700
  6600  4800  8150  4410  7686  2800  5948  4200  4520  4095  4120  5400
  4770  6300  5800  3000  2970  6720  4646 12900  3420  4995  4350  4160
  6040  6862  4815  7000  8100  3420  9166  6321 10240  6440  5170  6000
  3630  9667  5400  4320  3745  4160  3880  5680  2870  5010  4510  4000
  3840  3760  3640  2550  5320  5360  3520  8400  4100  4990  3510  3450
  9860  3520  4510  5885  4000  8250  4040  6360  3162  3510  3750  3968
  4900  2880  4880  4920  4950  3900  4500  1905  4075  3500  6450  4032
  4400 10360  3400  6360  6360  4500  2175  4360  7770  6650  2787  5500
  5040  5850  2610  2953  2747  4410  4000  2325  4600  3640  5800  7000
  4079  3520  2145  4500  8250  3450  4840  4080  4046  4632  5985  6060
  3600  3680  4040  5600  5900  4992  4340  3000  4320  3630  3460  5400
  4500  3460  4100  6480  4500  3960  4050  7260  5500  3000  3290  3816
  8080  2145  3780  3180  5300  3180  7152  4080  3850  2015  2176  3350
  3150  4820  3420  3600  5830  2856  8400  8250  2520  6930  3480  3600
  4040  6020  4050  3584  3120  5450  3630  3630  5640  3600  4280  3570
  3180  3000  3520  5960  4130  2850  2275  3520  4500  4000  3150  4500
  4500  3640  3850  4240  3650  4600  2135  3036  3990  7424  3480  3600
  3640  5900  3120  7350  3512  9500  5880 12944  4900  3060  5320  2145
  4000  3185  3850  2145  2610  1950  4040  4785  3450  3640  3500  4960
  4120  4750  3720  3750  3100  3185  2700  2145  4040  4775  2500  3180
  6060  3480  3792  4040  2145  5880  4500  3930  3640  4370  2684  4320
  3120  3450  3986  3500  4095  1650  3450  6750  9000  3069  4500  5495
  2398  3000  3850  3500  8100  4960  2160  3090  4500  3800  3090  3240
  2835  4600  5076  3750  3630  8050  4352  3000  5850  4960  3600  3660
  3480  2700  3150  6615  3040  3630  6000  5400  5200  3300  4350  2640
  2650  3960  6800  4000  4000  3934  2000  3630  2800  2430  3480  4000
  3185  4000  2910  3600  4400  3600  2880  3180  3000  4400  3000  3210
  3240  3000  3500  4840  7700  3635  2475  2787  3264  3640  3180  1836
  3970  3970  1950  5300  3000  2400  3000  3360  3420  1700  3649  2990
  3000  2400  3620  2910  3850]

In [32]:
print(col_price_area)

[[13300000     7420]
 [12250000     8960]
 [12250000     9960]
 ...
 [ 1750000     3620]
 [ 1750000     2910]
 [ 1750000     3850]]

### Summary statistics

For the price array and the area array, compute:
  - Mean
  - Median
  - Standard deviation
  - Maximum and minimum values

In [49]:
# Insert your code here
mean_val = np.mean(col_price)
median_val = np.median(col_price)
std_val = np.std(col_price)
max_val = np.max(col_price)
min_val = np.min(col_price)

# Print results
print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)
print("Maximum:", max_val)
print("Minimum:", min_val)

Mean: 4766729.247706422
Median: 4340000.0
Standard Deviation: 1868722.8281312082
Maximum: 13300000
Minimum: 1750000

### Normalization and Scaling
First, let's give a basic explanation these two fundamental concepts, without delving into the details:
 - **Normalization** is the process of rescaling values to a fixed range (0 to 1).
                    $$
                    x' = \frac{x - x_{\min}}{x_{\max} - x_{\min}}
                    $$

 - **Scaling** (or **standardization**) is the process of transforming data to have a mean of 0 and a standard deviation of 1.
                    $$
                    x' = \frac{x - \mu}{\sigma}
                    $$
(Recall: $\mu$ is the mean, $\sigma$ is the standard deviation). <br><br>

These strategies are used both for EDA (e.g., when you want to compare features that are in different ranges) and in methods that are necessary for machine learning and that we will see in the future lessons, such as Principal Component Analysis (PCA). <br><br>

Now, perform scaling and normalization: normalize the numeric column, and standardize the price column.
Hint: Implement directly the above formulae. Take this as an opportunity to **write your own function**, so that you can exercise! (Remember: Function start with `def function(parameters)`...)

> Remember that one huge advantage of NumPy is vectorization, and the fact that - differently from Python lists - you do not need to compute most operations element-wise (e.g. you don't need for loops!)

In [50]:
# Insert your code here
def normalize(arr):
    arr_norm = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
    return arr_norm

def scale(arr):
    arr_scaled = (arr - np.mean(arr)) / np.std(arr)
    return arr_scaled

In [51]:
print(normalize(col_price))
print(scale(col_price))

[1.         0.90909091 0.90909091 0.90606061 0.83636364 0.78787879
 0.72727273 0.72727273 0.7030303  0.6969697  0.6969697  0.68666667
 0.65454545 0.64848485 0.64848485 0.63636364 0.63636364 0.62424242
 0.61818182 0.61515152 0.60606061 0.6        0.5969697  0.5969697
 0.59090909 0.58787879 0.58121212 0.57575758 0.57575758 0.57575758
 0.57575758 0.57575758 0.56666667 0.55757576 0.55151515 0.54813333
 0.54484848 0.53939394 0.53787879 0.53333333 0.53030303 0.52727273
 0.51515152 0.51515152 0.5030303  0.5030303  0.5        0.4969697
 0.49393939 0.49090909 0.49090909 0.49090909 0.48484848 0.48484848
 0.48484848 0.48484848 0.48424242 0.47575758 0.47272727 0.47272727
 0.46666667 0.46060606 0.46060606 0.45757576 0.45454545 0.44848485
 0.44848485 0.44545455 0.44242424 0.43636364 0.43636364 0.43333333
 0.43030303 0.42727273 0.42424242 0.42424242 0.42424242 0.42424242
 0.42424242 0.42424242 0.42242424 0.42121212 0.42121212 0.41818182
 0.41212121 0.41212121 0.41212121 0.40909091 0.40909091 0.40606061
 0.40606061 0.40424242 0.4030303  0.39393939 0.39393939 0.39393939
 0.39393939 0.39393939 0.39333333 0.39090909 0.38787879 0.38787879
 0.38484848 0.38484848 0.38484848 0.38181818 0.38181818 0.37878788
 0.37727273 0.37575758 0.37575758 0.37575758 0.37515152 0.37515152
 0.36969697 0.36969697 0.36969697 0.36363636 0.36363636 0.36363636
 0.36363636 0.36363636 0.36363636 0.36363636 0.36363636 0.3630303
 0.35757576 0.35757576 0.3569697  0.3569697  0.35636364 0.35151515
 0.35151515 0.35151515 0.35090909 0.34848485 0.34545455 0.34545455
 0.34545455 0.34545455 0.34545455 0.33787879 0.33333333 0.33333333
 0.33333333 0.33333333 0.33333333 0.33333333 0.33333333 0.33333333
 0.33333333 0.33030303 0.33030303 0.32727273 0.32727273 0.32727273
 0.32666667 0.32424242 0.32424242 0.32121212 0.32121212 0.32121212
 0.32121212 0.31818182 0.31515152 0.31454545 0.30909091 0.30606061
 0.3030303  0.3030303  0.3030303  0.3030303  0.3030303  0.3030303
 0.3030303  0.3030303  0.3030303  0.30242424 0.30121212 0.3
 0.3        0.3        0.29393939 0.29393939 0.29090909 0.29090909
 0.29090909 0.29090909 0.28787879 0.28484848 0.28484848 0.28484848
 0.28484848 0.28424242 0.28181818 0.27878788 0.27878788 0.27757576
 0.27575758 0.27333333 0.27272727 0.27272727 0.27272727 0.27272727
 0.27272727 0.27272727 0.27272727 0.27272727 0.27272727 0.27272727
 0.27272727 0.27272727 0.27212121 0.27212121 0.26969697 0.26666667
 0.26666667 0.26666667 0.26666667 0.26363636 0.26363636 0.26121212
 0.26060606 0.26060606 0.26060606 0.26       0.25454545 0.25454545
 0.25454545 0.25454545 0.25454545 0.25454545 0.25151515 0.24848485
 0.24848485 0.24848485 0.24848485 0.24848485 0.24787879 0.24545455
 0.24545455 0.24242424 0.24242424 0.24242424 0.24242424 0.24242424
 0.24242424 0.24242424 0.24181818 0.24181818 0.23939394 0.23939394
 0.23939394 0.23939394 0.23636364 0.23636364 0.23636364 0.23636364
 0.23636364 0.23575758 0.23575758 0.23575758 0.23333333 0.23030303
 0.23030303 0.22969697 0.22969697 0.22969697 0.22787879 0.22727273
 0.22424242 0.22424242 0.22424242 0.22424242 0.22424242 0.22242424
 0.22121212 0.22121212 0.21878788 0.21818182 0.21818182 0.21818182
 0.21818182 0.21818182 0.21818182 0.21515152 0.21515152 0.21212121
 0.21212121 0.21212121 0.21212121 0.21212121 0.21212121 0.21212121
 0.21212121 0.21212121 0.21212121 0.21212121 0.21212121 0.21212121
 0.21212121 0.21212121 0.21212121 0.21212121 0.21151515 0.21151515
 0.20909091 0.20909091 0.20909091 0.20606061 0.20606061 0.20545455
 0.20333333 0.2030303  0.2030303  0.2030303  0.2        0.2
 0.2        0.2        0.2        0.1969697  0.1969697  0.1969697
 0.19545455 0.19545455 0.19393939 0.19393939 0.19393939 0.19393939
 0.19393939 0.18787879 0.18787879 0.18787879 0.18787879 0.18787879
 0.18787879 0.18787879 0.18484848 0.18484848 0.18181818 0.18181818
 0.18181818 0.18181818 0.18181818 0.18181818 0.18181818 0.18060606
 0.17878788 0.17575758 0.17575758 0.17575758 0.17575758 0.17575758
 0.17575758 0.17515152 0.17515152 0.17515152 0.17272727 0.16969697
 0.16969697 0.16969697 0.16969697 0.16969697 0.16909091 0.16909091
 0.16666667 0.16666667 0.16666667 0.16666667 0.16363636 0.16363636
 0.16363636 0.16363636 0.16363636 0.16363636 0.16363636 0.16363636
 0.16363636 0.1630303  0.16060606 0.16060606 0.15757576 0.15757576
 0.15757576 0.15757576 0.15454545 0.15151515 0.15151515 0.15151515
 0.15151515 0.15151515 0.15151515 0.15151515 0.15151515 0.15151515
 0.15151515 0.15151515 0.15151515 0.15151515 0.15151515 0.15151515
 0.15151515 0.15151515 0.15090909 0.14848485 0.14848485 0.14848485
 0.14545455 0.14545455 0.14545455 0.14545455 0.14545455 0.14545455
 0.14484848 0.14242424 0.14242424 0.14242424 0.13939394 0.13939394
 0.13939394 0.13939394 0.13939394 0.13939394 0.13939394 0.13939394
 0.13878788 0.1369697  0.13636364 0.13636364 0.13333333 0.13333333
 0.13333333 0.13333333 0.13333333 0.13333333 0.13333333 0.13333333
 0.13030303 0.13030303 0.12848485 0.12727273 0.12727273 0.12727273
 0.12727273 0.12121212 0.12121212 0.12121212 0.12121212 0.12121212
 0.12121212 0.12121212 0.12121212 0.12121212 0.12060606 0.11939394
 0.11851515 0.11818182 0.11818182 0.11818182 0.11575758 0.11515152
 0.11515152 0.11515152 0.11515152 0.11212121 0.10909091 0.10909091
 0.10909091 0.10909091 0.10909091 0.10909091 0.10909091 0.10848485
 0.10606061 0.10484848 0.1030303  0.1030303  0.1030303  0.1030303
 0.1030303  0.1030303  0.1030303  0.1030303  0.0969697  0.0969697
 0.0969697  0.0969697  0.09545455 0.09393939 0.09393939 0.09393939
 0.09090909 0.09090909 0.08484848 0.08484848 0.08181818 0.07878788
 0.07878788 0.07878788 0.07878788 0.07878788 0.07878788 0.07878788
 0.07818182 0.07818182 0.07393939 0.07272727 0.07272727 0.07272727
 0.06666667 0.06666667 0.06666667 0.06363636 0.06363636 0.06060606
 0.06060606 0.06060606 0.06060606 0.06060606 0.06060606 0.0569697
 0.05454545 0.05454545 0.05454545 0.05151515 0.04848485 0.04545455
 0.04545455 0.04545455 0.04242424 0.04181818 0.03333333 0.03030303
 0.03030303 0.03030303 0.01818182 0.01212121 0.01212121 0.00909091
 0.00606061 0.00148485 0.         0.         0.        ]
[ 4.56636513e+00  4.00448405e+00  4.00448405e+00  3.98575468e+00
  3.55497918e+00  3.25530927e+00  2.88072189e+00  2.88072189e+00
  2.73088693e+00  2.69342819e+00  2.69342819e+00  2.62974834e+00
  2.43121702e+00  2.39375829e+00  2.39375829e+00  2.31884081e+00
  2.31884081e+00  2.24392333e+00  2.20646459e+00  2.18773522e+00
  2.13154711e+00  2.09408838e+00  2.07535901e+00  2.07535901e+00
  2.03790027e+00  2.01917090e+00  1.97796629e+00  1.94425342e+00
  1.94425342e+00  1.94425342e+00  1.94425342e+00  1.94425342e+00
  1.88806531e+00  1.83187721e+00  1.79441847e+00  1.77351649e+00
  1.75321385e+00  1.71950099e+00  1.71013630e+00  1.68204225e+00
  1.66331288e+00  1.64458351e+00  1.56966604e+00  1.56966604e+00
  1.49474856e+00  1.49474856e+00  1.47601919e+00  1.45728982e+00
  1.43856045e+00  1.41983108e+00  1.41983108e+00  1.41983108e+00
  1.38237234e+00  1.38237234e+00  1.38237234e+00  1.38237234e+00
  1.37862647e+00  1.32618423e+00  1.30745486e+00  1.30745486e+00
  1.26999613e+00  1.23253739e+00  1.23253739e+00  1.21380802e+00
  1.19507865e+00  1.15761991e+00  1.15761991e+00  1.13889054e+00
  1.12016117e+00  1.08270243e+00  1.08270243e+00  1.06397306e+00
  1.04524369e+00  1.02651432e+00  1.00778496e+00  1.00778496e+00
  1.00778496e+00  1.00778496e+00  1.00778496e+00  1.00778496e+00
  9.96547334e-01  9.89055586e-01  9.89055586e-01  9.70326217e-01
  9.32867478e-01  9.32867478e-01  9.32867478e-01  9.14138109e-01
  9.14138109e-01  8.95408740e-01  8.95408740e-01  8.84171118e-01
  8.76679370e-01  8.20491262e-01  8.20491262e-01  8.20491262e-01
  8.20491262e-01  8.20491262e-01  8.16745389e-01  8.01761893e-01
  7.83032524e-01  7.83032524e-01  7.64303154e-01  7.64303154e-01
  7.64303154e-01  7.45573785e-01  7.45573785e-01  7.26844416e-01
  7.17479731e-01  7.08115046e-01  7.08115046e-01  7.08115046e-01
  7.04369173e-01  7.04369173e-01  6.70656308e-01  6.70656308e-01
  6.70656308e-01  6.33197569e-01  6.33197569e-01  6.33197569e-01
  6.33197569e-01  6.33197569e-01  6.33197569e-01  6.33197569e-01
  6.33197569e-01  6.29451695e-01  5.95738831e-01  5.95738831e-01
  5.91992957e-01  5.91992957e-01  5.88247083e-01  5.58280092e-01
  5.58280092e-01  5.58280092e-01  5.54534218e-01  5.39550723e-01
  5.20821353e-01  5.20821353e-01  5.20821353e-01  5.20821353e-01
  5.20821353e-01  4.73997930e-01  4.45903876e-01  4.45903876e-01
  4.45903876e-01  4.45903876e-01  4.45903876e-01  4.45903876e-01
  4.45903876e-01  4.45903876e-01  4.45903876e-01  4.27174507e-01
  4.27174507e-01  4.08445137e-01  4.08445137e-01  4.08445137e-01
  4.04699264e-01  3.89715768e-01  3.89715768e-01  3.70986399e-01
  3.70986399e-01  3.70986399e-01  3.70986399e-01  3.52257029e-01
  3.33527660e-01  3.29781786e-01  2.96068921e-01  2.77339552e-01
  2.58610183e-01  2.58610183e-01  2.58610183e-01  2.58610183e-01
  2.58610183e-01  2.58610183e-01  2.58610183e-01  2.58610183e-01
  2.58610183e-01  2.54864309e-01  2.47372561e-01  2.39880814e-01
  2.39880814e-01  2.39880814e-01  2.02422075e-01  2.02422075e-01
  1.83692706e-01  1.83692706e-01  1.83692706e-01  1.83692706e-01
  1.64963336e-01  1.46233967e-01  1.46233967e-01  1.46233967e-01
  1.46233967e-01  1.42488093e-01  1.27504598e-01  1.08775228e-01
  1.08775228e-01  1.01283481e-01  9.00458590e-02  7.50623635e-02
  7.13164897e-02  7.13164897e-02  7.13164897e-02  7.13164897e-02
  7.13164897e-02  7.13164897e-02  7.13164897e-02  7.13164897e-02
  7.13164897e-02  7.13164897e-02  7.13164897e-02  7.13164897e-02
  6.75706158e-02  6.75706158e-02  5.25871204e-02  3.38577510e-02
  3.38577510e-02  3.38577510e-02  3.38577510e-02  1.51283817e-02
  1.51283817e-02  1.44886277e-04 -3.60098759e-03 -3.60098759e-03
 -3.60098759e-03 -7.34686145e-03 -4.10597262e-02 -4.10597262e-02
 -4.10597262e-02 -4.10597262e-02 -4.10597262e-02 -4.10597262e-02
 -5.97890955e-02 -7.85184649e-02 -7.85184649e-02 -7.85184649e-02
 -7.85184649e-02 -7.85184649e-02 -8.22643387e-02 -9.72478342e-02
 -9.72478342e-02 -1.15977203e-01 -1.15977203e-01 -1.15977203e-01
 -1.15977203e-01 -1.15977203e-01 -1.15977203e-01 -1.15977203e-01
 -1.19723077e-01 -1.19723077e-01 -1.34706573e-01 -1.34706573e-01
 -1.34706573e-01 -1.34706573e-01 -1.53435942e-01 -1.53435942e-01
 -1.53435942e-01 -1.53435942e-01 -1.53435942e-01 -1.57181816e-01
 -1.57181816e-01 -1.57181816e-01 -1.72165311e-01 -1.90894681e-01
 -1.90894681e-01 -1.94640555e-01 -1.94640555e-01 -1.94640555e-01
 -2.05878176e-01 -2.09624050e-01 -2.28353419e-01 -2.28353419e-01
 -2.28353419e-01 -2.28353419e-01 -2.28353419e-01 -2.39591041e-01
 -2.47082789e-01 -2.47082789e-01 -2.62066284e-01 -2.65812158e-01
 -2.65812158e-01 -2.65812158e-01 -2.65812158e-01 -2.65812158e-01
 -2.65812158e-01 -2.84541527e-01 -2.84541527e-01 -3.03270897e-01
 -3.03270897e-01 -3.03270897e-01 -3.03270897e-01 -3.03270897e-01
 -3.03270897e-01 -3.03270897e-01 -3.03270897e-01 -3.03270897e-01
 -3.03270897e-01 -3.03270897e-01 -3.03270897e-01 -3.03270897e-01
 -3.03270897e-01 -3.03270897e-01 -3.03270897e-01 -3.03270897e-01
 -3.07016771e-01 -3.07016771e-01 -3.22000266e-01 -3.22000266e-01
 -3.22000266e-01 -3.40729635e-01 -3.40729635e-01 -3.44475509e-01
 -3.57586068e-01 -3.59459005e-01 -3.59459005e-01 -3.59459005e-01
 -3.78188374e-01 -3.78188374e-01 -3.78188374e-01 -3.78188374e-01
 -3.78188374e-01 -3.96917743e-01 -3.96917743e-01 -3.96917743e-01
 -4.06282428e-01 -4.06282428e-01 -4.15647113e-01 -4.15647113e-01
 -4.15647113e-01 -4.15647113e-01 -4.15647113e-01 -4.53105851e-01
 -4.53105851e-01 -4.53105851e-01 -4.53105851e-01 -4.53105851e-01
 -4.53105851e-01 -4.53105851e-01 -4.71835221e-01 -4.71835221e-01
 -4.90564590e-01 -4.90564590e-01 -4.90564590e-01 -4.90564590e-01
 -4.90564590e-01 -4.90564590e-01 -4.90564590e-01 -4.98056338e-01
 -5.09293959e-01 -5.28023328e-01 -5.28023328e-01 -5.28023328e-01
 -5.28023328e-01 -5.28023328e-01 -5.28023328e-01 -5.31769202e-01
 -5.31769202e-01 -5.31769202e-01 -5.46752698e-01 -5.65482067e-01
 -5.65482067e-01 -5.65482067e-01 -5.65482067e-01 -5.65482067e-01
 -5.69227941e-01 -5.69227941e-01 -5.84211436e-01 -5.84211436e-01
 -5.84211436e-01 -5.84211436e-01 -6.02940806e-01 -6.02940806e-01
 -6.02940806e-01 -6.02940806e-01 -6.02940806e-01 -6.02940806e-01
 -6.02940806e-01 -6.02940806e-01 -6.02940806e-01 -6.06686680e-01
 -6.21670175e-01 -6.21670175e-01 -6.40399544e-01 -6.40399544e-01
 -6.40399544e-01 -6.40399544e-01 -6.59128914e-01 -6.77858283e-01
 -6.77858283e-01 -6.77858283e-01 -6.77858283e-01 -6.77858283e-01
 -6.77858283e-01 -6.77858283e-01 -6.77858283e-01 -6.77858283e-01
 -6.77858283e-01 -6.77858283e-01 -6.77858283e-01 -6.77858283e-01
 -6.77858283e-01 -6.77858283e-01 -6.77858283e-01 -6.77858283e-01
 -6.81604157e-01 -6.96587652e-01 -6.96587652e-01 -6.96587652e-01
 -7.15317022e-01 -7.15317022e-01 -7.15317022e-01 -7.15317022e-01
 -7.15317022e-01 -7.15317022e-01 -7.19062896e-01 -7.34046391e-01
 -7.34046391e-01 -7.34046391e-01 -7.52775760e-01 -7.52775760e-01
 -7.52775760e-01 -7.52775760e-01 -7.52775760e-01 -7.52775760e-01
 -7.52775760e-01 -7.52775760e-01 -7.56521634e-01 -7.67759256e-01
 -7.71505130e-01 -7.71505130e-01 -7.90234499e-01 -7.90234499e-01
 -7.90234499e-01 -7.90234499e-01 -7.90234499e-01 -7.90234499e-01
 -7.90234499e-01 -7.90234499e-01 -8.08963868e-01 -8.08963868e-01
 -8.20201490e-01 -8.27693238e-01 -8.27693238e-01 -8.27693238e-01
 -8.27693238e-01 -8.65151976e-01 -8.65151976e-01 -8.65151976e-01
 -8.65151976e-01 -8.65151976e-01 -8.65151976e-01 -8.65151976e-01
 -8.65151976e-01 -8.65151976e-01 -8.68897850e-01 -8.76389598e-01
 -8.81821115e-01 -8.83881346e-01 -8.83881346e-01 -8.83881346e-01
 -8.98864841e-01 -9.02610715e-01 -9.02610715e-01 -9.02610715e-01
 -9.02610715e-01 -9.21340084e-01 -9.40069453e-01 -9.40069453e-01
 -9.40069453e-01 -9.40069453e-01 -9.40069453e-01 -9.40069453e-01
 -9.40069453e-01 -9.43815327e-01 -9.58798823e-01 -9.66290571e-01
 -9.77528192e-01 -9.77528192e-01 -9.77528192e-01 -9.77528192e-01
 -9.77528192e-01 -9.77528192e-01 -9.77528192e-01 -9.77528192e-01
 -1.01498693e+00 -1.01498693e+00 -1.01498693e+00 -1.01498693e+00
 -1.02435162e+00 -1.03371630e+00 -1.03371630e+00 -1.03371630e+00
 -1.05244567e+00 -1.05244567e+00 -1.08990441e+00 -1.08990441e+00
 -1.10863378e+00 -1.12736315e+00 -1.12736315e+00 -1.12736315e+00
 -1.12736315e+00 -1.12736315e+00 -1.12736315e+00 -1.12736315e+00
 -1.13110902e+00 -1.13110902e+00 -1.15733014e+00 -1.16482189e+00
 -1.16482189e+00 -1.16482189e+00 -1.20228062e+00 -1.20228062e+00
 -1.20228062e+00 -1.22100999e+00 -1.22100999e+00 -1.23973936e+00
 -1.23973936e+00 -1.23973936e+00 -1.23973936e+00 -1.23973936e+00
 -1.23973936e+00 -1.26221461e+00 -1.27719810e+00 -1.27719810e+00
 -1.27719810e+00 -1.29592747e+00 -1.31465684e+00 -1.33338621e+00
 -1.33338621e+00 -1.33338621e+00 -1.35211558e+00 -1.35586145e+00
 -1.40830369e+00 -1.42703306e+00 -1.42703306e+00 -1.42703306e+00
 -1.50195053e+00 -1.53940927e+00 -1.53940927e+00 -1.55813864e+00
 -1.57686801e+00 -1.60514936e+00 -1.61432675e+00 -1.61432675e+00
 -1.61432675e+00]

### Filtering
Select all rows where column area > mean of column area.

Count the number of rows where column area is above its median.

Replace all values lower than 4000 in the area column.

In [ ]:
# Insert your code here

#Select all rows where column area > mean of column area.


mean_area = np.mean(col_area)
# Select rows where A > mean
rows_area_gt_mean = col_area[col_area > mean_area]
print("Area > mean(area):\n", rows_area_gt_mean)

# Count the number of rows where column "area" is above its median.

median_area = np.median(col_area)
# Count rows where area > median
count_gt_median = np.sum(col_area > median_area)
print("Number of values for area > median(area):", count_gt_median)

# Replace all values lower than 4000 in the area column.

area_lt_4000 = np.where(col_area < 4000, 0, col_area)
print("Original array:", col_area)
print("Modified array:", area_lt_4000)

Area > mean(area):
 [ 7420  8960  9960  7500  7420  7500  8580 16200  8100  5750 13200  6000
  6550  7800  6000  6600  8500  6420  7155  8050  8800  6540  6000  8875
  7950  5500  7475  7000  5960  6840  7000  7482  9000  6000  6000  6550
  6360  6480  6000  6000  6000  6000  6600  7440  7440  6325  6000  6000
  6000 11440  9000  7680  6000  6000  8880  6240  6360 11175  8880 13200
  7700  6000 12090  6000  6600  6420  6500  5700  6000  6000 10500  6000
  8250  6670  7410  8580  6750  7200  6000  9000  6400  6600  6000  6600
  5500  5500  6350  5500  5450  6420  6615  6600  8372  9620  6800  8000
  6900  6420  7020  6540  7231  6254  7320  6525 15600  7160  6500  5500
 11460  5828  5200  7000  6000  5400  6360  5800  6660 10500 10500  5500
  6360  6600  5400  6100  6900  7980  6210  6100  6600  6825  6710  6450
  7800  6540  5500 10269  8400  5300  9800  8520  6050  7085  7200  7980
 11410  6100  5720  7600 10700  6600  8150  7686  5948  5400  6300  5800
  6720 12900  6040  6862  7000  8100  9166  6321 10240  6440  5170  6000
  9667  5400  5680  5320  5360  8400  9860  5885  8250  6360  6450 10360
  6360  6360  7770  6650  5500  5850  5800  7000  8250  5985  6060  5600
  5900  5400  6480  7260  5500  8080  5300  7152  5830  8400  8250  6930
  6020  5450  5640  5960  7424  5900  7350  9500  5880 12944  5320  6060
  5880  6750  9000  5495  8100  8050  5850  6615  6000  5400  5200  6800
  7700  5300]
Number of values for area > median(area): 268
Original array: [ 7420  8960  9960  7500  7420  7500  8580 16200  8100  5750 13200  6000
  6550  3500  7800  6000  6600  8500  4600  6420  4320  7155  8050  4560
  8800  6540  6000  8875  7950  5500  7475  7000  4880  5960  6840  7000
  7482  9000  6000  6000  6550  6360  6480  6000  6000  6000  6000  6600
  4300  7440  7440  6325  6000  5150  6000  6000 11440  9000  7680  6000
  6000  8880  6240  6360 11175  8880 13200  7700  6000 12090  4000  6000
  5020  6600  4040  4260  6420  6500  5700  6000  6000  4000 10500  6000
  3760  8250  6670  3960  7410  8580  5000  6750  4800  7200  6000  4100
  9000  6400  6600  6000  6600  5500  5500  6350  5500  4500  5450  6420
  3240  6615  6600  8372  4300  9620  6800  8000  6900  3700  6420  7020
  6540  7231  6254  7320  6525 15600  7160  6500  5500 11460  4800  5828
  5200  4800  7000  6000  5400  4640  5000  6360  5800  6660 10500  4800
  4700  5000 10500  5500  6360  6600  5136  4400  5400  3300  3650  6100
  6900  2817  7980  3150  6210  6100  6600  6825  6710  6450  7800  4600
  4260  6540  5500 10269  8400  5300  3800  9800  8520  6050  7085  3180
  4500  7200  3410  7980  3000  3000 11410  6100  5720  3540  7600 10700
  6600  4800  8150  4410  7686  2800  5948  4200  4520  4095  4120  5400
  4770  6300  5800  3000  2970  6720  4646 12900  3420  4995  4350  4160
  6040  6862  4815  7000  8100  3420  9166  6321 10240  6440  5170  6000
  3630  9667  5400  4320  3745  4160  3880  5680  2870  5010  4510  4000
  3840  3760  3640  2550  5320  5360  3520  8400  4100  4990  3510  3450
  9860  3520  4510  5885  4000  8250  4040  6360  3162  3510  3750  3968
  4900  2880  4880  4920  4950  3900  4500  1905  4075  3500  6450  4032
  4400 10360  3400  6360  6360  4500  2175  4360  7770  6650  2787  5500
  5040  5850  2610  2953  2747  4410  4000  2325  4600  3640  5800  7000
  4079  3520  2145  4500  8250  3450  4840  4080  4046  4632  5985  6060
  3600  3680  4040  5600  5900  4992  4340  3000  4320  3630  3460  5400
  4500  3460  4100  6480  4500  3960  4050  7260  5500  3000  3290  3816
  8080  2145  3780  3180  5300  3180  7152  4080  3850  2015  2176  3350
  3150  4820  3420  3600  5830  2856  8400  8250  2520  6930  3480  3600
  4040  6020  4050  3584  3120  5450  3630  3630  5640  3600  4280  3570
  3180  3000  3520  5960  4130  2850  2275  3520  4500  4000  3150  4500
  4500  3640  3850  4240  3650  4600  2135  3036  3990  7424  3480  3600
  3640  5900  3120  7350  3512  9500  5880 12944  4900  3060  5320  2145
  4000  3185  3850  2145  2610  1950  4040  4785  3450  3640  3500  4960
  4120  4750  3720  3750  3100  3185  2700  2145  4040  4775  2500  3180
  6060  3480  3792  4040  2145  5880  4500  3930  3640  4370  2684  4320
  3120  3450  3986  3500  4095  1650  3450  6750  9000  3069  4500  5495
  2398  3000  3850  3500  8100  4960  2160  3090  4500  3800  3090  3240
  2835  4600  5076  3750  3630  8050  4352  3000  5850  4960  3600  3660
  3480  2700  3150  6615  3040  3630  6000  5400  5200  3300  4350  2640
  2650  3960  6800  4000  4000  3934  2000  3630  2800  2430  3480  4000
  3185  4000  2910  3600  4400  3600  2880  3180  3000  4400  3000  3210
  3240  3000  3500  4840  7700  3635  2475  2787  3264  3640  3180  1836
  3970  3970  1950  5300  3000  2400  3000  3360  3420  1700  3649  2990
  3000  2400  3620  2910  3850]
Modified array: [ 7420  8960  9960  7500  7420  7500  8580 16200  8100  5750 13200  6000
  6550     0  7800  6000  6600  8500  4600  6420  4320  7155  8050  4560
  8800  6540  6000  8875  7950  5500  7475  7000  4880  5960  6840  7000
  7482  9000  6000  6000  6550  6360  6480  6000  6000  6000  6000  6600
  4300  7440  7440  6325  6000  5150  6000  6000 11440  9000  7680  6000
  6000  8880  6240  6360 11175  8880 13200  7700  6000 12090  4000  6000
  5020  6600  4040  4260  6420  6500  5700  6000  6000  4000 10500  6000
     0  8250  6670     0  7410  8580  5000  6750  4800  7200  6000  4100
  9000  6400  6600  6000  6600  5500  5500  6350  5500  4500  5450  6420
     0  6615  6600  8372  4300  9620  6800  8000  6900     0  6420  7020
  6540  7231  6254  7320  6525 15600  7160  6500  5500 11460  4800  5828
  5200  4800  7000  6000  5400  4640  5000  6360  5800  6660 10500  4800
  4700  5000 10500  5500  6360  6600  5136  4400  5400     0     0  6100
  6900     0  7980     0  6210  6100  6600  6825  6710  6450  7800  4600
  4260  6540  5500 10269  8400  5300     0  9800  8520  6050  7085     0
  4500  7200     0  7980     0     0 11410  6100  5720     0  7600 10700
  6600  4800  8150  4410  7686     0  5948  4200  4520  4095  4120  5400
  4770  6300  5800     0     0  6720  4646 12900     0  4995  4350  4160
  6040  6862  4815  7000  8100     0  9166  6321 10240  6440  5170  6000
     0  9667  5400  4320     0  4160     0  5680     0  5010  4510  4000
     0     0     0     0  5320  5360     0  8400  4100  4990     0     0
  9860     0  4510  5885  4000  8250  4040  6360     0     0     0     0
  4900     0  4880  4920  4950     0  4500     0  4075     0  6450  4032
  4400 10360     0  6360  6360  4500     0  4360  7770  6650     0  5500
  5040  5850     0     0     0  4410  4000     0  4600     0  5800  7000
  4079     0     0  4500  8250     0  4840  4080  4046  4632  5985  6060
     0     0  4040  5600  5900  4992  4340     0  4320     0     0  5400
  4500     0  4100  6480  4500     0  4050  7260  5500     0     0     0
  8080     0     0     0  5300     0  7152  4080     0     0     0     0
     0  4820     0     0  5830     0  8400  8250     0  6930     0     0
  4040  6020  4050     0     0  5450     0     0  5640     0  4280     0
     0     0     0  5960  4130     0     0     0  4500  4000     0  4500
  4500     0     0  4240     0  4600     0     0     0  7424     0     0
     0  5900     0  7350     0  9500  5880 12944  4900     0  5320     0
  4000     0     0     0     0     0  4040  4785     0     0     0  4960
  4120  4750     0     0     0     0     0     0  4040  4775     0     0
  6060     0     0  4040     0  5880  4500     0     0  4370     0  4320
     0     0     0     0  4095     0     0  6750  9000     0  4500  5495
     0     0     0     0  8100  4960     0     0  4500     0     0     0
     0  4600  5076     0     0  8050  4352     0  5850  4960     0     0
     0     0     0  6615     0     0  6000  5400  5200     0  4350     0
     0     0  6800  4000  4000     0     0     0     0     0     0  4000
     0  4000     0     0  4400     0     0     0     0  4400     0     0
     0     0     0  4840  7700     0     0     0     0     0     0     0
     0     0     0  5300     0     0     0     0     0     0     0     0
     0     0     0     0     0]

### Correlation
Compute the correlation coefficient between the area column and the price column using `np.corrcoef`.

In [58]:
# Insert your code here
corr_matrix = np.corrcoef(col_area, col_price)

print("Correlation matrix:\n", corr_matrix)

# Extract correlation coefficient between area and price
corr_area_price= corr_matrix[0, 1]
print("\nCorrelation coefficient between area and price:", corr_area_price)

Correlation matrix:
 [[1.         0.53599735]
 [0.53599735 1.        ]]

Correlation coefficient between area and price: 0.5359973457780797